/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorGenerateRouteImport } from './routes/creator.generate'
import { Route as CreatorLayersRouteImport } from './routes/creator.layers'
import { Route as CreatorNewRouteImport } from './routes/creator.new'
import { Route as CreatorWorkspaceRouteImport } from './routes/creator.workspace'
import { Route as DexIndexRouteImport } from './routes/dex.index'
import { Route as DexLiquidityRouteImport } from './routes/dex.liquidity'
import { Route as DexPoolsRouteImport } from './routes/dex.pools'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsHowItWorksRouteImport } from './routes/docs.how-it-works'
import { Route as DocsRoadmapRouteImport } from './routes/docs.roadmap'
import { Route as DocsTokenomicsRouteImport } from './routes/docs.tokenomics'
import { Route as DocsWhitepaperRouteImport } from './routes/docs.whitepaper'
import { Route as ApiPublicNftProjectIdImageRouteImport } from './routes/api/public/nft/$projectId/image'
import { Route as ApiPublicNftProjectIdImageTokenIdRouteImport } from './routes/api/public/nft/$projectId/image/$tokenId'
import { Route as ApiPublicNftProjectIdMetaTokenIdRouteImport } from './routes/api/public/nft/$projectId/meta/$tokenId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/creator/',
  path: '/creator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorGenerateRoute = CreatorGenerateRouteImport.update({
  id: '/creator/generate',
  path: '/creator/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorLayersRoute = CreatorLayersRouteImport.update({
  id: '/creator/layers',
  path: '/creator/layers',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorNewRoute = CreatorNewRouteImport.update({
  id: '/creator/new',
  path: '/creator/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorWorkspaceRoute = CreatorWorkspaceRouteImport.update({
  id: '/creator/workspace',
  path: '/creator/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DexIndexRoute = DexIndexRouteImport.update({
  id: '/dex/',
  path: '/dex/',
  getParentRoute: () => rootRouteImport,
} as any)
const DexLiquidityRoute = DexLiquidityRouteImport.update({
  id: '/dex/liquidity',
  path: '/dex/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const DexPoolsRoute = DexPoolsRouteImport.update({
  id: '/dex/pools',
  path: '/dex/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/docs/how-it-works',
  path: '/docs/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoadmapRoute = DocsRoadmapRouteImport.update({
  id: '/docs/roadmap',
  path: '/docs/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTokenomicsRoute = DocsTokenomicsRouteImport.update({
  id: '/docs/tokenomics',
  path: '/docs/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWhitepaperRoute = DocsWhitepaperRouteImport.update({
  id: '/docs/whitepaper',
  path: '/docs/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNftProjectIdImageRoute =
  ApiPublicNftProjectIdImageRouteImport.update({
    id: '/api/public/nft/$projectId/image',
    path: '/api/public/nft/$projectId/image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNftProjectIdImageTokenIdRoute =
  ApiPublicNftProjectIdImageTokenIdRouteImport.update({
    id: '/$tokenId',
    path: '/$tokenId',
    getParentRoute: () => ApiPublicNftProjectIdImageRoute,
  } as any)
const ApiPublicNftProjectIdMetaTokenIdRoute =
  ApiPublicNftProjectIdMetaTokenIdRouteImport.update({
    id: '/api/public/nft/$projectId/meta/$tokenId',
    path: '/api/public/nft/$projectId/meta/$tokenId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/stake': typeof StakeRoute
  '/creator/generate': typeof CreatorGenerateRoute
  '/creator/layers': typeof CreatorLayersRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/workspace': typeof CreatorWorkspaceRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/pools': typeof DexPoolsRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/tokenomics': typeof DocsTokenomicsRoute
  '/docs/whitepaper': typeof DocsWhitepaperRoute
  '/creator/': typeof CreatorIndexRoute
  '/dex/': typeof DexIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/nft/$projectId/image': typeof ApiPublicNftProjectIdImageRouteWithChildren
  '/api/public/nft/$projectId/image/$tokenId': typeof ApiPublicNftProjectIdImageTokenIdRoute
  '/api/public/nft/$projectId/meta/$tokenId': typeof ApiPublicNftProjectIdMetaTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/stake': typeof StakeRoute
  '/creator/generate': typeof CreatorGenerateRoute
  '/creator/layers': typeof CreatorLayersRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/workspace': typeof CreatorWorkspaceRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/pools': typeof DexPoolsRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/tokenomics': typeof DocsTokenomicsRoute
  '/docs/whitepaper': typeof DocsWhitepaperRoute
  '/creator': typeof CreatorIndexRoute
  '/dex': typeof DexIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/public/nft/$projectId/image': typeof ApiPublicNftProjectIdImageRouteWithChildren
  '/api/public/nft/$projectId/image/$tokenId': typeof ApiPublicNftProjectIdImageTokenIdRoute
  '/api/public/nft/$projectId/meta/$tokenId': typeof ApiPublicNftProjectIdMetaTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/stake': typeof StakeRoute
  '/creator/generate': typeof CreatorGenerateRoute
  '/creator/layers': typeof CreatorLayersRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/workspace': typeof CreatorWorkspaceRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/pools': typeof DexPoolsRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/tokenomics': typeof DocsTokenomicsRoute
  '/docs/whitepaper': typeof DocsWhitepaperRoute
  '/creator/': typeof CreatorIndexRoute
  '/dex/': typeof DexIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/nft/$projectId/image': typeof ApiPublicNftProjectIdImageRouteWithChildren
  '/api/public/nft/$projectId/image/$tokenId': typeof ApiPublicNftProjectIdImageTokenIdRoute
  '/api/public/nft/$projectId/meta/$tokenId': typeof ApiPublicNftProjectIdMetaTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/marketplace'
    | '/portfolio'
    | '/projects'
    | '/stake'
    | '/creator/generate'
    | '/creator/layers'
    | '/creator/new'
    | '/creator/workspace'
    | '/dex/liquidity'
    | '/dex/pools'
    | '/docs/how-it-works'
    | '/docs/roadmap'
    | '/docs/tokenomics'
    | '/docs/whitepaper'
    | '/creator/'
    | '/dex/'
    | '/docs/'
    | '/api/public/nft/$projectId/image'
    | '/api/public/nft/$projectId/image/$tokenId'
    | '/api/public/nft/$projectId/meta/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/marketplace'
    | '/portfolio'
    | '/projects'
    | '/stake'
    | '/creator/generate'
    | '/creator/layers'
    | '/creator/new'
    | '/creator/workspace'
    | '/dex/liquidity'
    | '/dex/pools'
    | '/docs/how-it-works'
    | '/docs/roadmap'
    | '/docs/tokenomics'
    | '/docs/whitepaper'
    | '/creator'
    | '/dex'
    | '/docs'
    | '/api/public/nft/$projectId/image'
    | '/api/public/nft/$projectId/image/$tokenId'
    | '/api/public/nft/$projectId/meta/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/marketplace'
    | '/portfolio'
    | '/projects'
    | '/stake'
    | '/creator/generate'
    | '/creator/layers'
    | '/creator/new'
    | '/creator/workspace'
    | '/dex/liquidity'
    | '/dex/pools'
    | '/docs/how-it-works'
    | '/docs/roadmap'
    | '/docs/tokenomics'
    | '/docs/whitepaper'
    | '/creator/'
    | '/dex/'
    | '/docs/'
    | '/api/public/nft/$projectId/image'
    | '/api/public/nft/$projectId/image/$tokenId'
    | '/api/public/nft/$projectId/meta/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  StakeRoute: typeof StakeRoute
  CreatorGenerateRoute: typeof CreatorGenerateRoute
  CreatorLayersRoute: typeof CreatorLayersRoute
  CreatorNewRoute: typeof CreatorNewRoute
  CreatorWorkspaceRoute: typeof CreatorWorkspaceRoute
  DexLiquidityRoute: typeof DexLiquidityRoute
  DexPoolsRoute: typeof DexPoolsRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsRoadmapRoute: typeof DocsRoadmapRoute
  DocsTokenomicsRoute: typeof DocsTokenomicsRoute
  DocsWhitepaperRoute: typeof DocsWhitepaperRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  DexIndexRoute: typeof DexIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiPublicNftProjectIdImageRoute: typeof ApiPublicNftProjectIdImageRouteWithChildren
  ApiPublicNftProjectIdMetaTokenIdRoute: typeof ApiPublicNftProjectIdMetaTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/creator'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/generate': {
      id: '/creator/generate'
      path: '/creator/generate'
      fullPath: '/creator/generate'
      preLoaderRoute: typeof CreatorGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/layers': {
      id: '/creator/layers'
      path: '/creator/layers'
      fullPath: '/creator/layers'
      preLoaderRoute: typeof CreatorLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/new': {
      id: '/creator/new'
      path: '/creator/new'
      fullPath: '/creator/new'
      preLoaderRoute: typeof CreatorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/workspace': {
      id: '/creator/workspace'
      path: '/creator/workspace'
      fullPath: '/creator/workspace'
      preLoaderRoute: typeof CreatorWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/': {
      id: '/dex/'
      path: '/dex'
      fullPath: '/dex/'
      preLoaderRoute: typeof DexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/liquidity': {
      id: '/dex/liquidity'
      path: '/dex/liquidity'
      fullPath: '/dex/liquidity'
      preLoaderRoute: typeof DexLiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/pools': {
      id: '/dex/pools'
      path: '/dex/pools'
      fullPath: '/dex/pools'
      preLoaderRoute: typeof DexPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/docs/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/roadmap': {
      id: '/docs/roadmap'
      path: '/docs/roadmap'
      fullPath: '/docs/roadmap'
      preLoaderRoute: typeof DocsRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tokenomics': {
      id: '/docs/tokenomics'
      path: '/docs/tokenomics'
      fullPath: '/docs/tokenomics'
      preLoaderRoute: typeof DocsTokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/whitepaper': {
      id: '/docs/whitepaper'
      path: '/docs/whitepaper'
      fullPath: '/docs/whitepaper'
      preLoaderRoute: typeof DocsWhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft/$projectId/image': {
      id: '/api/public/nft/$projectId/image'
      path: '/api/public/nft/$projectId/image'
      fullPath: '/api/public/nft/$projectId/image'
      preLoaderRoute: typeof ApiPublicNftProjectIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft/$projectId/image/$tokenId': {
      id: '/api/public/nft/$projectId/image/$tokenId'
      path: '/$tokenId'
      fullPath: '/api/public/nft/$projectId/image/$tokenId'
      preLoaderRoute: typeof ApiPublicNftProjectIdImageTokenIdRouteImport
      parentRoute: typeof ApiPublicNftProjectIdImageRoute
    }
    '/api/public/nft/$projectId/meta/$tokenId': {
      id: '/api/public/nft/$projectId/meta/$tokenId'
      path: '/api/public/nft/$projectId/meta/$tokenId'
      fullPath: '/api/public/nft/$projectId/meta/$tokenId'
      preLoaderRoute: typeof ApiPublicNftProjectIdMetaTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicNftProjectIdImageRouteChildren {
  ApiPublicNftProjectIdImageTokenIdRoute: typeof ApiPublicNftProjectIdImageTokenIdRoute
}

const ApiPublicNftProjectIdImageRouteChildren: ApiPublicNftProjectIdImageRouteChildren =
  {
    ApiPublicNftProjectIdImageTokenIdRoute:
      ApiPublicNftProjectIdImageTokenIdRoute,
  }

const ApiPublicNftProjectIdImageRouteWithChildren =
  ApiPublicNftProjectIdImageRoute._addFileChildren(
    ApiPublicNftProjectIdImageRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  StakeRoute: StakeRoute,
  CreatorGenerateRoute: CreatorGenerateRoute,
  CreatorLayersRoute: CreatorLayersRoute,
  CreatorNewRoute: CreatorNewRoute,
  CreatorWorkspaceRoute: CreatorWorkspaceRoute,
  DexLiquidityRoute: DexLiquidityRoute,
  DexPoolsRoute: DexPoolsRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsRoadmapRoute: DocsRoadmapRoute,
  DocsTokenomicsRoute: DocsTokenomicsRoute,
  DocsWhitepaperRoute: DocsWhitepaperRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  DexIndexRoute: DexIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiPublicNftProjectIdImageRoute: ApiPublicNftProjectIdImageRouteWithChildren,
  ApiPublicNftProjectIdMetaTokenIdRoute: ApiPublicNftProjectIdMetaTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
